---
title: "R Notebook - as used in class"
output: html_notebook
---

Notebook used in class + a few changes to experiment.
Changes are marked with comments.

R notebook: Face Recognition using Multi-layer Feedforward Neural Network

```{r}
library(pixmap)  
library(gdata)

# Always start with a clean environment to avoid subtle bugs
rm(list = ls())

set.seed(1234)
```

```{r}
left1<-read.pnm(file="faces/fromclass/left/left1.pgm")
plot(left1)
```

```{r}
left1.matrix<-left1@grey
left1
```

```{r}
left1.vector<-unmatrix(left1.matrix,byrow=T)
left1.frame<-data.frame(left1.vector)
left1.frame
dim(left1.frame)
```

```{r}
loadImages <- function(pathName,fileNames, clasLabel) {
files<-list.files(path=pathName,pattern=fileNames,all.files=T,full.names=T,no..=T)
print(files)
list_of_images=lapply(files,read.pnm)
plot(list_of_images[[1]])
n.images<-length(list_of_images)
image.matrix<-list_of_images[[1]]@grey
image.vector<-unmatrix(image.matrix,byrow=T)
for(ii in 2:n.images)
{
 i.matrix<-list_of_images[[ii]]@grey
 i.vector<-unmatrix(i.matrix,byrow=T)
 image.vector<-rbind(image.vector,i.vector)
}
image.frame<-data.frame(image.vector)
n.rows<-nrow(image.frame)
class1.label<-rep(clasLabel,n.rows)
image.frame<-cbind(image.frame,class1.label)
return (image.frame)
}

```

```{r}
left.frame <- loadImages("~/fau/cap6619/homework2/faces/fromclass/left","left.*",1)
left.frame
```
```{r}
right.frame <- loadImages("~/fau/cap6619/homework2/faces/fromclass/right","right.*",-1)
right.frame


```

```{r}
total.frame<-rbind(left.frame,right.frame)
dim(total.frame)

```
```{r}

train.index<-sample(nrow(total.frame),nrow(total.frame)*0.6)

training.set<-total.frame[train.index,]
training.set

test.set<-total.frame[-train.index,]
test.set
```

```{r}
library(neuralnet)

myform <- as.formula(paste('class1.label ~ ',paste(names(training.set[!names(training.set) %in% 'class1.label']), collapse = ' + ')))
face.classifier <- neuralnet(myform, training.set, hidden = 2, rep=100, linear.output = FALSE, threshold = 0.1)
summary(face.classifier)
```
```{r}
class.index<-length(test.set)
face.prediction<-compute(face.classifier,test.set[,-class.index])
face.prediction$net.result
```


```{r}
classifications<-ifelse(face.prediction$net.result>0.5,1,-1)
classifications
```

```{r}
table(test.set[,class.index],classifications)
```

# Start of my changes -------------------------------------------------------------------

Code modified to select the best repetition (smallest error).

```{r}
best <- which.min(face.classifier$result.matrix["error",])
cat("Best repetition:", best, "\n\n")
```

```{r}
class.index<-length(test.set)
face.prediction<-compute(face.classifier,test.set[,-class.index], rep = best)
face.prediction$net.result
```

```{r}
classifications<-ifelse(face.prediction$net.result>0.5,1,-1)
classifications
table(test.set[,class.index],classifications)
```

```{r}
table(test.set[,class.index],classifications)
```

# End of my changes

```{r}
face.4.3.classifier <- neuralnet(myform, training.set, hidden = c(4,3), rep=1000, linear.output = FALSE, threshold = 0.1)
face.prediction<-compute(face.4.3.classifier,test.set[,-class.index])
face.prediction$net.result
classifications<-ifelse(face.prediction$net.result>0.5,1,-1)
classifications
```

```{r}
table(test.set[,class.index],classifications)
```

